#!/bin/sh
set -eu

if [ -z "${OPENWEBUI_POSTGRES_DB:-}" ] || [ -z "${OPENWEBUI_POSTGRES_USER:-}" ] || [ -z "${OPENWEBUI_POSTGRES_PASSWORD:-}" ]; then
  echo "[openwebui-db-init] skip: one of OPENWEBUI_POSTGRES_* vars is empty"
  exit 0
fi

psql -v ON_ERROR_STOP=1 <<EOSQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${OPENWEBUI_POSTGRES_USER}') THEN
    CREATE ROLE ${OPENWEBUI_POSTGRES_USER} LOGIN PASSWORD '${OPENWEBUI_POSTGRES_PASSWORD}';
  ELSE
    ALTER ROLE ${OPENWEBUI_POSTGRES_USER} WITH PASSWORD '${OPENWEBUI_POSTGRES_PASSWORD}';
  END IF;
END
\$\$;

SELECT 'CREATE DATABASE ${OPENWEBUI_POSTGRES_DB} OWNER ${OPENWEBUI_POSTGRES_USER}'
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = '${OPENWEBUI_POSTGRES_DB}')\gexec

ALTER DATABASE ${OPENWEBUI_POSTGRES_DB} OWNER TO ${OPENWEBUI_POSTGRES_USER};
GRANT ALL PRIVILEGES ON DATABASE ${OPENWEBUI_POSTGRES_DB} TO ${OPENWEBUI_POSTGRES_USER};
EOSQL

echo "[openwebui-db-init] OpenWebUI DB bootstrap complete"
